# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               REACCH Decision Tool
tagline:             'Data you can use'
description:         'A decision tool for agricultural consultants'
url:                 http://mtpain.github.io/decision_tool
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Good Life Institute of Northern Idaho
  url:               https://www.reacchpna.org/
  email:             maturner01@gmail.com

# Custom vars
version:             1.0.0
